language: generic
services: 
    - docker

before_install:
    - docker build -t chyngyzsydykov/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true chyngyzsydykov/docker-react npm run test

