language: generic
services: 
    - docker

before_install:
    - echo -e "echoing some text"
    - docker build -t chyngyzsydykov/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true chyngyzsydykov/docker-react npm run test

deploy: 
    provider: elasticbeanstalk
    region: "eu-central-1"
    app: docker-react"
    env: "DockerReact-env"
    bucker_name: "elasticbeanstalk-eu-central-1-159457461041"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_ACCESS_SECRET